---
# Install pmm-dump, always overwrite the version before with latest

- name: Download pmm-dump binary (tech preview)
  get_url:
    url: https://github.com/percona/pmm-dump/releases/download/0.5.1-beta/pmm-transferer
    dest: /tmp/pmm-transferer
    tmp_dest: /tmp/
    force: yes
    headers:
      Accept: "application/octet-stream"

- name: Install the binary and rename to pmm-dump
  copy:
    src: /tmp/pmm-transferer
    dest: "/usr/local/bin/pmm-dump"
    owner: root
    group: root
    mode: "0755"
    remote_src: yes
  become: true

- name: Remove the file from /tmp
  file:
    path: /tmp/pmm-transferer
    state: absent
