---
# Install pmm-dump, always overwrite the version before with latest
# Percona tool, see https://github.com/percona/pmm-dump/releases/download/0.5.1-beta/pmm-transferer

- name: Download pmm-dump binary (tech preview)
  get_url:
    url: https://github.com/percona/pmm-dump/releases/download/0.5.1-beta/pmm-transferer
    dest: /usr/local/bin/pmm-dump
    checksum: "sha1:e431359d0c4d6f0b4a54b71ec9766b0e5ff45287"
    force: yes
    owner: root
    group: root
    mode: "0755"
    headers:
      Accept: "application/octet-stream"
  become: true
