dist: bionic
language: go
os: linux

services:
  - docker

go:
  - 1.16.x
  - tip

jobs:
  allow_failures:
    - go: tip

cache:
  directories:
    - /home/travis/.cache/go-build
    # - /home/travis/gopath/pkg

before_cache:
  - go clean -testcache
  # - go clean -cache

# skip non-trunk PMM-XXXX/SAAS-XXXX branch builds, but still build pull requests
branches:
  except:
    - /^PMM\-\d{3,5}/
    - /^SAAS\-\d{2,5}/

go_import_path: github.com/percona/pmm-update

env:
  global:
    - CODECOV_ENV=PMM_SERVER_IMAGE

    # REVIEWDOG_GITHUB_API_TOKEN
    - secure: d7wrZeZWD6fYyUVbu2/p/QqCTs6isXfAyV8uUOZeb+qnKxYAz56URVwiZTmZW4zWSR3dpe81RmAtAJRGQa0LOBeoqkdjBiO38PQylbLO4rbQrC/I+4q3/BqN4GKIuPcX0eCNNNw7qryz/Dx3n8tm6D179y/Ilc8vCOo6EHRawPNHvdA10OsBdL6WfSfEVx69FRqz39dgaqeZxM/w3d5ra32s+mVsn0ja+gtGJFg+qzI/nHyN90Pkn6XweED/Pn3YAjrK+bEkTCJ53RbnNZf+/80p386VnrrhTKuEBE15DOtKQKINPcG+8C1n46sDD6VBUWAO3MI5BjYwXgTIZCGsHDnEzR7n6yUIsfhc2497xuqc+auKjUlrcafTPZTnBf74OY5mx0w+4hWn8qkC3Z03oNZfHhx/yGz8h8aEQBAoBigVKGc5qInD4AlEu692061IsIvWqmvU/rgiyiFuwLqFBt2+ivi3XrukI+DthWTlyF0nRuLyxoRojQ1/1VLDNL+s1KAVWjuZySvBH4tmslGeFgDTbcs3RcQxzZIC8aBAIuEecibiPY7bUwdNc9lr/JKXFLwrnK0yvLePGD5rBQc3K3lZdUYnabuGRekfUOsLmYsT62kME/DpPruuUa7Al0/YHXahC2lYFCV3rcopUXVeyDvK3zGMRDnFtQVU4rcVtAQ=

  matrix:
    - PMM_SERVER_IMAGE=percona/pmm-server:2.0.0 # oldest production version
    - PMM_SERVER_IMAGE=percona/pmm-server:2.16.0 # version with enabled expirimental repo
    - PMM_SERVER_IMAGE=percona/pmm-server:2 # latest production version
    - PMM_SERVER_IMAGE=public.ecr.aws/e7j3v3n0/pmm-server:dev-latest # latest development version

before_install:
  - docker-compose up -d
  - docker exec pmm-update-server /root/go/src/github.com/percona/pmm-update/.devcontainer/install-dev-tools.sh

install: skip

before_script:
  #- make init It-s already run from install-dev-tools.sh
  - make format
  - git status
  - git diff --exit-code

script:
  - docker exec pmm-update-server make -C /root/go/src/github.com/percona/pmm-update ci-reviewdog
  - docker exec pmm-update-server make -C /root/go/src/github.com/percona/pmm-update install

  - docker exec pmm-update-server make -C /root/go/src/github.com/percona/pmm-update test-cover
  - docker exec pmm-update-server make -C /root/go/src/github.com/percona/pmm-update test-race

  - docker exec pmm-update-server make -C /root/go/src/github.com/percona/pmm-update check

  - docker exec pmm-update-server make -C /root/go/src/github.com/percona/pmm-update
    run-race-cover RUN_FLAGS='-debug -check'

  # ignore first possible self-update exit
  - docker exec pmm-update-server make -C /root/go/src/github.com/percona/pmm-update
    run-race-cover RUN_FLAGS='-debug -perform -playbook=/root/go/src/github.com/percona/pmm-update/ansible/playbook/tasks/update.yml'
    || true
  - docker exec pmm-update-server make -C /root/go/src/github.com/percona/pmm-update
    run-race-cover RUN_FLAGS='-debug -perform -playbook=/root/go/src/github.com/percona/pmm-update/ansible/playbook/tasks/update.yml'

after_success:
  - curl https://codecov.io/bash > codecov
  - chmod +x codecov
  - ./codecov -f cover.out -F cover -X fix
  - ./codecov -f *.runcover.out -F runcover -X fix

notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      - secure: POSDV4dcuoIbRBYXRKIHGHBf9KvvJcGlmHEIJN9Hokw/PCxQ217zJ3/cC9FmGtOORYpKunqnuEXSSc6IgmGjPMZXap9KStpHHn3PidO2FaBQFLdCvEJF5B3TcL2nM0CgZUVwtyoQi9ecv2TJxqllHEsTs8BAr0rSe1UHWEcQamZlYGR7mzFjLNu6z8m1c1eUGvkV0KplzXgCGxmMV+TCCr9I296MLuvXSu2xKuh4aqxji4puXBjA54SHml6oegcu+nRYIcoew+A2MjOgA0cYIU/S9hOvHunpmb4pNSml7OOrjaB73kzQ59clDaopA2Ehy4szRQexq0eDmYIhSR1DvUyEXjr/dHrJz/5/j68kvFNj/9CFaXpmPY395AVyFZEatOC5wEpj7AnEQNzKVOQKQZbaXqCWE+MVtj+v2npqzUiRVCtgGQn3h1RZVZ+qUfkvGBqKzVDQYpOR/dZb+aomLndTt5IBuWIZc0XTIrPNur0i/IIriCdvPZtrRA9eBxYFGKmFdcQIM1iZLk5oXVycOS8v5v+y3MDY9VFmarRL2AF81qiaGZJWNQqJMrgnb/wlLnjVjRr5mqxm+cda+DZe78jpDwkUA9IiiY7HEOFNG8rtNFLAP2ToSga4OgP0W45djMno8hRGO/gNq1SHU6f1qmdfIc8SMVOnXrj3Grr1Fmg=
