---
version: '3'
services:
  pmm-update-server:
    image: ${PMM_SERVER_IMAGE:-percona/pmm-server:2}
    container_name: pmm-update-server
    environment:
      # for tests
      - PMM_SERVER_IMAGE=${PMM_SERVER_IMAGE:-percona/pmm-server:2}
      - GO_VERSION=${GO_VERSION:-1.17.x}
      - PATH=/root/go/bin:$PATH
      - TRAVIS_REPO_SLUG=${TRAVIS_REPO_SLUG}
      - TRAVIS_PULL_REQUEST_SHA=${TRAVIS_PULL_REQUEST_SHA}
      - TRAVIS_COMMIT=${TRAVIS_COMMIT}
      - TRAVIS_PULL_REQUEST_BRANCH=${TRAVIS_PULL_REQUEST_BRANCH}
      - TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST}
      - REVIEWDOG_GITHUB_API_TOKEN=${REVIEWDOG_GITHUB_API_TOKEN}
    volumes:
      - .:/root/go/src/github.com/percona/pmm-update
