---
# This roles contains tasks executed during initialization PMM Server
- name: Get current version
  slurp:
    src: /srv/grafana/PERCONA_DASHBOARDS_VERSION
  register: current_version_file
  ignore_errors: True

- name: Get image version
  slurp:
    src: /usr/share/percona-dashboards/VERSION
  register: image_version_file

- name: Set current version if VERSION fail doen't exist
  set_fact:
      pmm_current_version: "0.0"
  when: current_version_file['failed'] == true

- name: Setting current and image version
  set_fact:
    pmm_current_version: "{{ current_version_file['content'] | b64decode | trim }}"
  when: current_version_file['failed'] != true

- name: Setting current and image version
  set_fact:
    pmm_image_version: "{{ image_version_file['content'] | b64decode | trim }}"

- name: Print current version
  debug:
    msg: "Current version: {{ pmm_current_version }} Image Version: {{ pmm_image_version }}"

- name: Checking if we need an update or not
  meta: end_play
  when: pmm_current_version is version(pmm_image_version, '>=')

- name: Synchronization plugin
  synchronize:
    src: /usr/share/percona-dashboards/panels/
    dest: /srv/grafana/plugins/
  delegate_to: "{{ inventory_hostname }}"

- name: Restart grafana with new plugins
  supervisorctl:
    name: grafana
    state: restarted

- name: Copy file with image version
  copy:
    src: /usr/share/percona-dashboards/VERSION
    dest: /srv/grafana/PERCONA_DASHBOARDS_VERSION
    remote_src: yes
