---
# This role contains tasks executed during initialization PMM Server
- name: Get current version
  slurp:
    src: /srv/grafana/PERCONA_DASHBOARDS_VERSION
  register: current_version_file
  ignore_errors: True

- name: Get image version
  slurp:
    src: /usr/share/percona-dashboards/VERSION
  register: image_version_file

- name: Set current version if VERSION fail doen't exist
  set_fact:
      pmm_current_version: "0.0"
  when: current_version_file['failed'] == true

- name: Setting current and image version
  set_fact:
    pmm_current_version: "{{ current_version_file['content'] | b64decode | trim }}"
  when: current_version_file['failed'] != true

- name: Setting current and image version
  set_fact:
    pmm_image_version: "{{ image_version_file['content'] | b64decode | trim }}"

- name: Create backup directory
  file:
    path: /srv/backup
    state: directory

- name: Create grafana database
  postgresql_db:
    name: grafana
    state: present
  register: database_exists

- name: Migrate Grafana database from SQLite to Postgresql
  include_role:
    name: sqlite-to-postgres
  when: database_exists.changed

- name: Print current version
  debug:
    msg: "Current version: {{ pmm_current_version }} Image Version: {{ pmm_image_version }}"

- name: Checking if we need an update or not
  include_role:
    name: dashboards_upgrade
  when: not pmm_current_version is version(pmm_image_version, '>=')
