---
# Install Postgres
- name: Create Postgres data dir
  file:
    path: "/srv/postgres14"
    state: directory
    owner: postgres
    group: postgres

- name: Add PostgreSQL YUM repository
  yum_repository:
    name: percona-ppg-14
    description: PostgreSQL YUM repository - x86_64
    baseurl: http://repo.percona.com/ppg-14/yum/release/7/RPMS/x86_64
    gpgcheck: yes
    enabled: yes
    gpgkey: file:///etc/pki/rpm-gpg/PERCONA-PACKAGING-KEY

- name: Add PostgreSQL YUM repository
  yum_repository:
    name: percona-ppg-11
    description: PostgreSQL YUM repository - x86_64
    baseurl: http://repo.percona.com/ppg-11/yum/release/7/RPMS/x86_64
    gpgcheck: yes
    enabled: yes
    gpgkey: file:///etc/pki/rpm-gpg/PERCONA-PACKAGING-KEY

- name: Clean yum cache
  command: yum clean all

- name: Install Postgres
  yum:
    name:
      - percona-postgresql14-server
      - percona-postgresql14-contrib
      - percona-postgresql14
      - percona-postgresql11-server
      - percona-postgresql11-contrib
      - percona-postgresql11
    state: installed

- name: Create Postgres log file
  file:
    path: /srv/logs/postgresql14.log
    state: touch
    force: yes
    group: postgres
    owner: postgres
    mode: 0644

- name: Add the user 'postgres' to group 'pmm'
  user:
    name: postgres
    groups: pmm
    append: yes

- name: Check if Postgres 11 exist
  stat:
    path: /srv/postgres
  register: is_postgres_11

- name: Upgrade postgres from 11 to 14
  block:
    - name: Create Postgres data cluster
      command: su postgres -c "/usr/pgsql-14/bin/initdb -D /srv/postgres14"

    - name: Stop pmm-managed and postgres before changing encoding
      supervisorctl:
        name: "{{ item }}"
        state: stopped
      loop:
        - pmm-managed
        - postgres

    - name: Run Postgres database without supervisor
      command: /usr/pgsql-11/bin/pg_ctl start -D /srv/postgres
      become_user: postgres

    - name: Dump pmm-managed database
      postgresql_db:
        name: pmm-managed
        state: dump
        target: /tmp/pmm-managed-upgrade.sql

    - name: Stop Postgres database without supervisor
      command: /usr/pgsql-11/bin/pg_ctl stop -D /srv/postgres
      become_user: postgres

    - name: Start Postgres 14 database without supervisor
      command: /usr/pgsql-14/bin/pg_ctl stop -D /srv/postgres14
      become_user: postgres

    - name: Create pmm-managed database
      postgresql_db:
        name: pmm-managed
        state: present

    - name: Restore pmm-managed database
      postgresql_db:
        name: pmm-managed
        state: restore
        target: /tmp/pmm-managed-upgrade.sql

    - name: Remove old postgres packages
      yum:
        name:
          - percona-postgresql11-server
          - percona-postgresql11-contrib
          - percona-postgresql11
          - percona-postgresql11-libs
        state: absent

    - name: Delete old repo file
      file:
        state: absent
        path: "/etc/yum.repos.d/percona-ppg-11.repo"

    - name: Rename old Postgres directory
      copy:
        remote_src: true
        src: /srv/postgres
        dest: /srv/postgres_old
  when: is_postgres_11.stat.exists

- name: Disable logging_collector
  lineinfile:
    path: /srv/postgres14/postgresql.conf
    regexp: '^logging_collector'
    line: 'logging_collector = off'
