apiVersion: 1
datasources:
- name: Metrics
  version: 2
  orgId: 1
  type: prometheus
  access: proxy
  url: http://${VICTORIAMETRICS_HOST}/prometheus/
  isDefault: true
  jsonData:
    httpMethod: POST
    keepCookies: []
    timeInterval: 1s
- name: PostgreSQL
  version: 2
  orgId: 1
  type: postgres
  access: proxy
  url: ${PMM_POSTGRES_HOSTNAME}
  user: ${PMM_POSTGRES_USER}
  password: ${PMM_POSTGRES_PASS}
  database: pmm-managed
  jsonData:
    postgresVersion: "1100"
    sslmode: disable
- name: ClickHouse
  version: 2
  orgId: 1
  type: vertamedia-clickhouse-datasource
  access: proxy
  url: http://${PMM_CLICKHOUSE_HOST}:${PMM_CLICKHOUSE_PORT}
  jsonData:
    keepCookies: []
- name: PTSummary
  version: 2
  orgId: 1
  type: pmm-pt-summary-datasource
  access: proxy
- name: Prometheus AlertManager
  version: 2
  orgId: 1
  type: camptocamp-prometheus-alertmanager-datasource
  access: proxy
  url: http://localhost:9093/alertmanager/
  jsonData:
    keepCookies: []
