---
- name: Create grafana directory
  file:
    path: "{{ item }}"
    state: directory
    owner: grafana
    group: grafana
    mode: '0775'
  loop:
    - /srv/grafana
    - /srv/grafana/plugins

- name: Set Grafana folder for plugins on /srv partition for all users
  lineinfile:
    path: /etc/bashrc
    line: 'export GF_PLUGIN_DIR=/srv/grafana/plugins'

- name: Set needed Grafana plugins with fixed versions
  lineinfile:
    path: /etc/bashrc
    line: 'export GF_INSTALL_PLUGINS="camptocamp-prometheus-alertmanager-datasource 1.0.0,grafana-piechart-panel 1.6.2,grafana-polystat-panel 1.2.11,grafana-worldmap-panel 0.3.3,jdbranham-diagram-panel 1.7.3,natel-discrete-panel 0.1.1,petrslavotinek-carpetplot-panel 0.1.2,vertamedia-clickhouse-datasource 2.4.4,yesoreyeram-boomtable-panel 1.4.1"'

- name: Copy new version of grafana.ini
  copy:
    src: grafana.ini
    dest: /etc/grafana/grafana.ini
    owner: grafana
    group: grafana
    mode: '0444'

- name: Create provisioning directory
  file:
    path: "/usr/share/grafana/conf/provisioning/{{ item }}"
    owner: grafana
    group: grafana
    state: directory
  loop:
    - datasources
    - plugins
    - dashboards

- name: Copy grafana provisioning files
  copy:
    src: "{{ item }}.yml"
    dest: "/usr/share/grafana/conf/provisioning/{{ item }}/default.yml"
    owner: grafana
    group: grafana
  loop:
    - datasources
    - plugins
    - dashboards

- name: Upgrade grafana database (Get the latest schema)
  command: grafana-cli --homepath=/usr/share/grafana admin data-migration encrypt-datasource-passwords
  changed_when: True
