---
- name: Create Grafana backup dir
  file:
    path: "{{ grafana_backup_dir }}"
    state: directory
    owner: grafana
    group: grafana
    mode: '0700'

- name: Stop grafana before upgrade
  supervisorctl:
    name: 'grafana'
    state: stopped

- name: Create grafana user
  postgresql_user:
    db: grafana
    name: grafana
    password: grafana
    priv: 'ALL'
    expires: infinity
    state: present
  when: not ansible_check_mode

- name: Create actual grafana config
  include_role:
    name: grafana

- name: Start grafana again
  supervisorctl:
    name: grafana
    state: started

- name: Check if initail data were created
  postgresql_query:
    db: grafana
    query: SELECT 1 FROM org WHERE id=1
  retries: 3
  delay: 3
  register: psql_result
  until: psql_result.rowcount == 1

- name: wait for grafana database initiazation
  pause:
    seconds: 10

- name: Stop grafana before upgrade
  supervisorctl:
    name: 'grafana'
    state: stopped

- name: Install grafana-migrate
  yum:
    name: "grafana-db-migrator"
    state: latest

- name: Run grafana migrator
  command: grafana-db-migrator /srv/grafana/grafana.db "postgres://grafana:grafana@localhost:5432/grafana?sslmode=disable"
  register: migrator_output
  changed_when: "'All done' in migrator_output.stdout"

- name: Start grafana again
  supervisorctl:
    name: grafana
    state: started

- name: Create backup for SQLite Grafana database
  copy:
    src: /srv/grafana/grafana.db
    dest: "{{ grafana_backup_dir }}/grafana.db"
    owner: grafana
    group: grafana
    mode: '0700'

- name: Remove SQLite Grafana database
  file:
    path: /srv/grafana/grafana.db
    state: absent