---
- name: Create Grafana backup dir
  file:
    path: "{{ grafana_backup_dir }}"
    state: directory
    owner: grafana
    group: grafana
    mode: '0700'

- name: Stop grafana before upgrade
  supervisorctl:
    name: 'grafana'
    state: stopped

- name: Create actual grafana config and grafana db
  include_role:
    name: grafana

- name: Start grafana again
  supervisorctl:
    name: grafana
    state: restarted
  ignore_errors: yes

- name: Check if initial data were created
  postgresql_query:
    db: grafana
    query: SELECT 1 FROM org WHERE id=1
  retries: 3
  delay: 3
  register: psql_result
  until: psql_result.rowcount == 1
  when: not ansible_check_mode

- name: wait for grafana database initiazation
  pause:
    seconds: 10

- name: Stop grafana before upgrade
  supervisorctl:
    name: grafana
    state: stopped

- name: Install grafana-migrate
  yum:
    name: "grafana-db-migrator"
    state: latest
  ignore_errors: yes # TODO DELETE BEFORE RELEASE

- name: Run grafana migrator
  command: grafana-db-migrator --change-char-to-text --reset-home-dashboard /srv/grafana/grafana.db "postgres://grafana:grafana@localhost:5432/grafana?sslmode=disable"
  register: migrator_output
  changed_when: "'All done' in migrator_output.stdout"

- name: Start grafana again
  supervisorctl:
    name: grafana
    state: restarted
  ignore_errors: yes

- name: Display grafana.log content
  command: cat /srv/logs/grafana.log
  register: command_output

- name: Create backup for SQLite Grafana database
  copy:
    src: /srv/grafana/grafana.db
    dest: "{{ grafana_backup_dir }}/grafana.db"
    owner: grafana
    group: grafana
    mode: '0700'

- name: Remove SQLite Grafana database
  file:
    path: /srv/grafana/grafana.db
    state: absent
